### PR TITLE
Madeoftech

### PR DESCRIPTION
**Pull request by fphilippe**
Many modifications so that container will work better, faster, on a smaller machine or a wider area, and with up to date images.

### CODE REVIEW

**Comment by joe-akeem** [comment]
@fphilippe I get errors when I run it as described in the `README` 🤔 

```
gdaldem hillshade -z 5 /data/tif/contour-3785.tif /data/tif/hillshade.tif
madeoftech-contour-tiles-contour-tiles-1  | 0ERROR 1: LZWDecode:Wrong length of decoded string: data probably corrupted at scanline 17664
madeoftech-contour-tiles-contour-tiles-1  | ERROR 1: TIFFReadEncodedTile() failed.
madeoftech-contour-tiles-contour-tiles-1  | ERROR 1: /data/tif/contour-3785.tif, band 1: IReadBlock failed at X offset 69, Y offset 0: TIFFReadEncodedTile() failed.
```
```
gdaldem slope /data/tif/contour-3785.tif /data/tif/slope.tif
madeoftech-contour-tiles-contour-tiles-1  | 0ERROR 1: LZWDecode:Wrong length of decoded string: data probably corrupted at scanline 17664
madeoftech-contour-tiles-contour-tiles-1  | ERROR 1: TIFFReadEncodedTile() failed.
madeoftech-contour-tiles-contour-tiles-1  | ERROR 1: /data/tif/contour-3785.tif, band 1: IReadBlock failed at X offset 69, Y offset 0: TIFFReadEncodedTile() failed.
```

```
madeoftech-contour-tiles-contour-tiles-1  | gdal_contour -f PostgreSQL -nln contourlines -a elev -i 20 /data/tif/contour-3785.tif "PG:host=postgres-osm port=5432 dbname=gis user=contour password=passwd"
madeoftech-contour-tiles-contour-tiles-1  | 0ERROR 1: LZWDecode:Wrong length of decoded string: data probably corrupted at scanline 17664
madeoftech-contour-tiles-contour-tiles-1  | ERROR 1: TIFFReadEncodedTile() failed.
madeoftech-contour-tiles-contour-tiles-1  | ERROR 1: /data/tif/contour-3785.tif, band 1: IReadBlock failed at X offset 69, Y offset 0: TIFFReadEncodedTile() failed.
madeoftech-contour-tiles-contour-tiles-1  | make: *** [Makefile:87: /data/contour2pgsql-contour] Error 1
```

**Comment by fphilippe** [comment]
Hi @joe-akeem, i suspect a cache problem... Last time, you had the same problem with an issue i open. Did you ran a totally new image with all the data i put in the PR ?

On my side, I've just ran a test from scratch without any problem 👍 

```
contour-tiles_1  | gdal_merge.py -co COMPRESS=LZW -co BIGTIFF=YES -co PREDICTOR=2 -co TILED=YES -o /data/tif/contour-4326.tif /data/tif/srtm_34_02.tif /data/tif/srtm_35_01.tif /data/tif/srtm_35_02.tif /data/tif/srtm_35_03.tif /data/tif/srtm_35_04.tif /data/tif/srtm_35_05.tif 
/data/tif/srtm_36_01.tif /data/tif/srtm_36_02.tif /data/tif/srtm_36_03.tif /data/tif/srtm_36_04.tif /data/tif/srtm_36_05.tif /data/tif/srtm_37_01.tif /data/tif/srtm_37_02.tif /data/tif/srtm_37_03.tif /data/tif/srtm_37_04.tif /data/tif/srtm_37_05.tif /data/tif/srtm_38_01.tif /data/tif/srtm_38_02.tif /data/tif/srtm_38_03.tif /data/tif/srtm_38_04.tif /data/tif/srtm_38_05.tif /data/tif/srtm_39_01.tif /data/tif/srtm_39_02.tif /data/tif/srtm_39_03.tif /data/tif/srtm_39_04.tif /data/tif/srtm_39_05.tif /data/tif/srtm_40_01.tif /data/tif/srtm_40_02.tif /data/tif/srtm_40_03.tif /data/tif/srtm_40_04.tif /data/tif/srtm_40_05.tif
contour-tiles_1  | 0...10...20...30...40...50...60...70...80...90...100 - done.
contour-tiles_1  | mkdir -p /data/tif
contour-tiles_1  | gdalwarp -co COMPRESS=LZW -co BIGTIFF=YES -co PREDICTOR=2 -co TILED=YES -s_srs EPSG:4326 -t_srs EPSG:3785 -r bilinear /data/tif/contour-4326.tif /data/tif/contour-3785.tif
contour-tiles_1  | Creating output file that is 34942P x 37988L.
contour-tiles_1  | Processing /data/tif/contour-4326.tif [1/1] : 0...10...20...30...40...50...60...70...80...90...100 - done.
contour-tiles_1  | mkdir -p /data/tif
contour-tiles_1  | gdaldem hillshade -z 5 /data/tif/contour-3785.tif /data/tif/hillshade.tif
contour-tiles_1  | 0...10...20...30...40...50...60...70...80...90...100 - done.
```

**Comment by fphilippe** [comment]
Hi @joe-akeem, did you had the time to test once again ?

**Comment by joe-akeem** [comment]
> Hi @joe-akeem, did you had the time to test once again ?

Hi @fphilippe, unfortunately I still can't get it to work. I just completely cleaned all docker images and the all files untracked by git and started it again according to your new description in README. I keep getting the same error:

`madeoftech-contour-tiles-contour-tiles-1  | ERROR 1: /data/tif/contour-3785.tif, band 1: IReadBlock failed at X offset 69, Y offset 0: TIFFReadEncodedTile() failed.`

**Comment by fphilippe** [comment]
Hi @joe-akeem, i guess it's a problem related to the compression. could you try to modify the var GDAL_COMPRESS_OPTIONS in makefile to :
GDAL_COMPRESS_OPTIONS := 
It will disable the compression. It will be a first step to diagnose the problem.

By the way, it doesn't answer the question : why does it work on my terraformed vm every time i launch it from scratch meanwhile it doesn't on your configuration...

**Comment by joe-akeem** [comment]
I had suspected that with the compression too from googling a bit but removing it didn't help. However, it worked on my Linux machine. So probably something with the setup on my notebook 🤷 I will merge it like this! Thanks a lot for the contribution, @fphilippe !

**Pull request merged**
